DROP TABLE IF EXISTS users, films, friends, likes, genres, mpas,
                comedies, dramas, cartoons, thrillers, documentaries, actions;


CREATE TABLE users
(
    id int generated by default as identity primary key,
    name varchar(255),
    login varchar(255),
    email varchar(255),
    birthday varchar(64)
);

CREATE TABLE friends
(
    id int generated by default as identity primary key,
    user_id_from int,
    user_id_to int,
    accepted boolean
);

CREATE TABLE films
(
    id int generated by default as identity primary key,
    name varchar(255),
    description varchar(255),
    releaseDate varchar(64),
    duration int,
    mpa_id int
);

CREATE TABLE mpas
(
    id int generated by default as identity primary key,
    name varchar(32)
);

CREATE TABLE likes
(
    id int generated by default as identity primary key,
    film_id int,
    user_id int
);

CREATE TABLE genres
(
    id int generated by default as identity primary key,
    name varchar(32),
    table_name varchar(32)
);

CREATE TABLE comedies
(
    id int generated by default as identity primary key,
    film_id int
);

CREATE TABLE dramas
(
    id int generated by default as identity primary key,
    film_id int
);

CREATE TABLE cartoons
(
    id int generated by default as identity primary key,
    film_id int
);

CREATE TABLE thrillers
(
    id int generated by default as identity primary key,
    film_id int
);

CREATE TABLE documentaries
(
    id int generated by default as identity primary key,
    film_id int
);

CREATE TABLE actions
(
    id int generated by default as identity primary key,
    film_id int
);