DROP TABLE IF EXISTS users, films, friends, likes, genres, mpas,
                comedies, dramas, cartoons, thrillers, documentaries, actions;

CREATE TABLE users
(
    name varchar(255),
    login varchar(255) not null,
    email varchar(255) not null,
    birthday varchar(64) not null,
    id int generated by default as identity primary key
);

CREATE TABLE friends
(
    user_id_from int,
    user_id_to int,
    accepted boolean,
    id int generated by default as identity primary key
);

CREATE TABLE films
(
    name varchar(255) not null,
    description varchar(255) not null,
    releaseDate varchar(64) not null,
    duration int,
    mpa_id int,
    id int generated by default as identity primary key
);

CREATE TABLE mpas
(
    name varchar(32),
    id int generated by default as identity primary key
);

CREATE TABLE likes
(
    film_id int,
    user_id int,
    id int generated by default as identity primary key
);

CREATE TABLE genres
(
    name varchar(32) not null,
    table_name varchar(32) not null,
    id int generated by default as identity primary key
);

CREATE TABLE comedies
(
    film_id int,
    id int generated by default as identity primary key
);

CREATE TABLE dramas
(
    film_id int,
    id int generated by default as identity primary key
);

CREATE TABLE cartoons
(
    film_id int,
    id int generated by default as identity primary key
);

CREATE TABLE thrillers
(
    film_id int,
    id int generated by default as identity primary key
);

CREATE TABLE documentaries
(
    film_id int,
    id int generated by default as identity primary key
);

CREATE TABLE actions
(
    film_id int,
    id int generated by default as identity primary key
);